### ISSUE TITLE
Dockerfile - run jar in background

### ISSUE THREAD

**Issue by gaetanoziri** [GruppoPBDMNG-10/url-shortener#9]

**Comment by fabiofumarola** [comment]
you can add the command as [cmd](https://docs.docker.com/reference/builder/#cmd) or entrypoint in the [dockerfile](https://docs.docker.com/reference/builder/#entrypoint)

[What is the difference between CMD and ENTRYPOINT in a Dockerfile?](http://stackoverflow.com/questions/21553353/what-is-the-difference-between-cmd-and-entrypoint-in-a-dockerfile)
